kind: Pod
apiVersion: v1
metadata:
  name: velpod
  
spec:
  containers:
    - name: v1
      image: 'centos:7'
      command: [ "ping", "localhost" ] 

    - name: v2
      image: 'httpd'
      ports:
        - containerPort: 80  
